### ISSUE TITLE
&amp; in title of contact or group

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-theme#929]
If the symbol of "&" is used in the name of a contact or group, it displays as "&amp;" in many places like members list. eg. Terry (&amp; Sandy) Kernel 

For a group the same issue happens eg. Surf &amp; Skate group

**Comment by corsacca** [comment]
@mikeallbutt can you make a list of the places this happens? Does it always happen?

**Comment by mikeallbutt** [comment]
> @mikeallbutt can you make a list of the places this happens? Does it always happen?

It happens in a few places but not everywhere.

- Name column on the contacts and groups list page
- Contact title in the contact details tile
- Group title in the group details tile
- In the member list in the Members tile, if a member has the symbol in their name
- In the various fields of the Connections tile - Groups, Relation and all the auto-suggest names in all the fields.

Interestingly, when you go to edit the details for the contact or group, the name is written correctly.

**Comment by corsacca** [comment]
@mikeallbutt Can you provide steps to reproduce the issue? It displays correctly with my test:
![image](https://user-images.githubusercontent.com/24901539/79315479-e826c480-7efa-11ea-9717-a657ac8f58d3.png)

**Comment by micahmills** [comment]
I was not seeing this in my local DT instance but when I looked on my instance in disciple.tools I was seeing this problem. Apparently something that we have done since the latest update has fixed this, and it should be resolved when we roll out the next update.

**Comment by corsacca** [comment]
@mikeallbutt can you confirm that this is still an issue? 
Any ways we can reproduce it?

**Comment by mikeallbutt** [comment]
@corsacca and @micahmills where are we up to with this long standing issue?

**Comment by ahillbilly** [comment]
I think that they think it was fixed and need to know where it is still an issue if it is.

**Comment by mikeallbutt** [comment]
@ahillbilly & @corsacca 

> I think that they think it was fixed and need to know where it is still an issue if it is.

This is still an issue. It is in the details tile and the name field of the list page - this is for both Contacts and Groups.

**Comment by ahillbilly** [comment]
After a bit of investigating, there are two ways of half fixing it, but they haven't figured out a safe way of fixing both at the same time... much of the current work being done could affect this issue, so it will need to stay on hold while the other is completed and then be re-addressed.

**Comment by corsacca** [comment]
Issue resolved for all titles going forward.
